# This file contains values from Cookiecutter

default_context:
  project_name: "medulla-db"
  project_description: "Vector Database plugin for Medulla"
  organization: "Utkarsh Kanwat"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "Medulla-ML"
  email: "utkarshkanwat@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
